---

name: "Release"
run-name: "Release"

on:
  push:
  # release:
  #   types:
  #     - created
  #     - released
  #     - published
  #     - prereleased

permissions:
  actions: none
  artifact-metadata: write
  attestations: write
  checks: write
  contents: read
  deployments: read
  id-token: none
  issues: none
  models: none
  discussions: write
  packages: write
  pages: none
  pull-requests: none
  security-events: none
  statuses: none

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

env:
  CONFIGURATION: Release
  SOLUTION_NAME: 'StopWatch.sln'
  WIX_PROJ_FILE: 'source/StopWatchSetup/StopWatchSetup.wixproj'

jobs:
  release:
    name: "Release"
    runs-on: windows-latest
    steps:

      - id: checkout
        name: "Checkout"
        uses: actions/checkout@v6

      - id: setup-dotnet
        name: "Setup Dotnet"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - id: build-app
        name: "Build App"
        run: dotnet build --configuration "$env:CONFIGURATION" "$env:SOLUTION_NAME"

      - id: build-installer
        name: "Build Installer"
        run: dotnet build --configuration "$env:CONFIGURATION" "$env:WIX_PROJ_FILE"

      - id: upload-release-artifact
        name: "Archive Release"
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: |
            **/*.msi
